---
title: hiree
email: contact@hiree.app
description: ''
baseurl: ''
url: https://hiree.app
twitter_username: jekyllrb
github_username: jekyll
plugins:
- jekyll-feed
collections:
  pages:
    output: true
