---
label: Default
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: permalink
  type: text
  config:
    required: false
  label: permalink
  description: Link to the page, has to start with /<br>Should be empty for the main
    page
- type: field_group
  name: header
  label: Header
  fields:
  - type: text
    name: title
    label: title
  - type: textarea
    name: subtitle
    label: subtitle
    config:
      wysiwyg: true
      schema:
        format: html
- type: field_group
  name: usp
  label: USP
  fields:
  - type: textarea
    name: title
    label: title
    config:
      wysiwyg: true
      schema:
        format: html
  - type: field_group_list
    name: items
    label: items
    fields:
    - type: text
      name: button
      label: button
    - type: textarea
      name: desc
      label: desc
      config:
        wysiwyg: true
        schema:
          format: html
    - type: file
      name: icon
      label: icon
    - type: text
      name: id
      label: id
  - type: boolean
    name: show
    label: show
- type: field_group_list
  name: main_content
  label: Main Text Sections
  fields:
  - type: field_group_list
    name: row
    label: row
    fields:
    - type: text
      name: title
      label: title
    - type: textarea
      name: text
      label: text
      config:
        wysiwyg: true
        schema:
          format: html
  - type: file
    name: img
    label: img
  - type: boolean
    name: show
    label: show
  - name: joboffer_graphic
    type: boolean
    label: Job Offer Graphic
  - name: loup_graphic
    type: boolean
    label: Loup Graphic
  - name: skills_graphic
    type: boolean
    label: Skills Graphic
- type: field_group
  name: features
  label: Feature Cards
  fields:
  - type: text
    name: title
    label: title
  - type: field_group_list
    name: cards
    label: cards
    fields:
    - type: text
      name: desc
      label: desc
    - type: text
      name: icon
      label: icon
  - type: boolean
    name: show
    label: show
- type: field_group
  name: about
  label: About
  fields:
  - type: text
    name: title
    label: title
  - type: field_group_list
    name: paragraphs
    label: paragraphs
    fields:
    - type: textarea
      name: text
      label: text
      config:
        wysiwyg: true
        schema:
          format: html
  - type: boolean
    name: show
    label: show
- name: layout
  type: text
  config:
    required: false
  label: layout
  default: default
  hidden: true
- type: text
  name: download_text
  label: download_text
pages:
- index.md
